name: Formatting Checks
on: [push, pull_request]

jobs:
  clang-format:
    name: Check C++ formatting with ClangFormat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run clang-format
        run: find src/ -iname *.h -o -iname *.cpp | xargs clang-format-13 -n --Werror --style=file

  # black:
  #   name: Check Python formatting with Black
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         submodules: recursive
  #     - name: Run black
  #       run: find src/ -iname *.py | xargs black --check
